### ISSUE TITLE
How to filter by object type

### ISSUE THREAD

**Issue by towolf** [cloud66/copper#6]
If I have a fake concatenated manifest (in this case the output of `helm template), the I find it tricky to filter on object types. 

```yaml
---
apiVersion: v1
kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
---
apiVersion: v1
kind: ConfigMap
---
apiVersion: v1
kind: Service
---
apiVersion: apps/v1beta1
kind: Deployment
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
```

Aside, the tool recognizes the first element as an empty doc, I think.

How do I enforce things for `kind: Service` only?
